"""Seeded SF Bay Area job-training and placement programs for HerPath v0.

These are real, publicly-known programs at the time of writing (May 2026)
with information aggregated from their public websites. URLs are included
so a HerPath user can take the next step directly. In a production build
we would pull live program data via a partnership API or weekly scraper.
"""

PROGRAMS = [
    {
        "id": "p01",
        "name": "Upwardly Global — Bay Area",
        "url": "https://www.upwardlyglobal.org/",
        "city": "Remote / SF Bay Area",
        "format": "Online + cohort coaching",
        "duration": "8–12 weeks",
        "cost": "Free",
        "level": "professional",
        "fields": ["software engineering", "data analytics", "finance", "healthcare admin", "project management"],
        "audience": "Internationally-trained professionals with work authorization in the U.S.",
        "outcomes": "Resume rewrite, interview prep, U.S. employer network, placement coaching",
        "languages": ["English"],
        "next_step": "Apply for cohort intake at upwardlyglobal.org/job-seekers",
    },
    {
        "id": "p02",
        "name": "Jewish Vocational Service (JVS) — Bay Area Career Connect",
        "url": "https://www.jvs.org/",
        "city": "San Francisco",
        "format": "In-person + hybrid",
        "duration": "Varies (4–24 weeks)",
        "cost": "Free for eligible participants",
        "level": "entry to mid",
        "fields": ["healthcare (CNA, MA)", "tech support", "accounting", "early childhood education"],
        "audience": "Open to all, including immigrants and refugees regardless of religion",
        "outcomes": "Industry certification + direct employer referrals (Sutter, UCSF, Genentech)",
        "languages": ["English"],
        "next_step": "Attend a JVS info session — schedule at jvs.org",
    },
    {
        "id": "p03",
        "name": "Refugee & Immigrant Forum of Solano County (RIFSC) — Workforce",
        "url": "https://www.rifsc.org/",
        "city": "Fairfield / Solano County",
        "format": "In-person",
        "duration": "Rolling enrollment",
        "cost": "Free",
        "level": "entry",
        "fields": ["customer service", "warehouse / logistics", "home health aide", "ESL-supported jobs"],
        "audience": "Refugees, asylees, and immigrant women",
        "outcomes": "ESL-integrated job training, on-the-job English support, placement",
        "languages": ["English", "Arabic", "Dari", "Farsi", "Pashto", "Spanish", "Tigrinya"],
        "next_step": "Walk in to the Fairfield office or call (707) 422-2008",
    },
    {
        "id": "p04",
        "name": "International Rescue Committee (IRC) — Oakland Workforce",
        "url": "https://www.rescue.org/united-states/oakland-ca",
        "city": "Oakland",
        "format": "In-person + hybrid",
        "duration": "Rolling",
        "cost": "Free",
        "level": "entry",
        "fields": ["food service", "healthcare support", "childcare", "hospitality"],
        "audience": "Refugees and humanitarian-status immigrants",
        "outcomes": "Job-readiness training, employer matching, work-authorization help",
        "languages": ["English", "Spanish", "Arabic", "Dari", "Pashto", "Ukrainian"],
        "next_step": "Email economic.empowerment@rescue.org or call IRC Oakland",
    },
    {
        "id": "p05",
        "name": "Code Tenderloin — Code Ramp",
        "url": "https://www.codetenderloin.org/",
        "city": "San Francisco",
        "format": "In-person",
        "duration": "12 weeks",
        "cost": "Free",
        "level": "entry to mid",
        "fields": ["software engineering", "front-end web development", "QA testing"],
        "audience": "SF residents, including immigrant women, no prior coding required",
        "outcomes": "Coding bootcamp + paid apprenticeship pipeline with partner employers",
        "languages": ["English"],
        "next_step": "Apply at codetenderloin.org/code-ramp",
    },
    {
        "id": "p06",
        "name": "Hack the Hood",
        "url": "https://www.hackthehood.org/",
        "city": "Oakland",
        "format": "In-person + remote",
        "duration": "6-week bootcamp",
        "cost": "Free + stipend",
        "level": "entry",
        "fields": ["digital marketing", "web development", "tech career exploration"],
        "audience": "Young women of color (16–25), including immigrant youth",
        "outcomes": "Paid bootcamp + small-business client work portfolio",
        "languages": ["English", "Spanish"],
        "next_step": "Apply at hackthehood.org/program-info",
    },
    {
        "id": "p07",
        "name": "Year Up Bay Area",
        "url": "https://www.yearup.org/",
        "city": "San Francisco / San Jose",
        "format": "In-person + hybrid",
        "duration": "12 months (6 mo training + 6 mo internship)",
        "cost": "Free + weekly stipend",
        "level": "entry to mid",
        "fields": ["IT / cybersecurity", "software development", "finance ops", "data analytics"],
        "audience": "Adults 18–29 with HS diploma; immigrant young women strongly encouraged",
        "outcomes": "Internship at Bank of America, Google, LinkedIn, Salesforce, etc.; ~85% placement",
        "languages": ["English"],
        "next_step": "Apply at yearup.org/admissions",
    },
    {
        "id": "p08",
        "name": "Renaissance Entrepreneurship Center — Women's Business Program",
        "url": "https://www.rencenter.org/",
        "city": "San Francisco / East Palo Alto / Richmond",
        "format": "In-person + online",
        "duration": "14 weeks",
        "cost": "Sliding scale ($0–$300)",
        "level": "any (women starting businesses)",
        "fields": ["small business", "food / catering", "retail", "consulting"],
        "audience": "Women, especially low-income and immigrant women",
        "outcomes": "Business plan, microloan access, peer cohort, mentor network",
        "languages": ["English", "Spanish"],
        "next_step": "Attend an info session at rencenter.org",
    },
    {
        "id": "p09",
        "name": "Kitchen Town — Food Entrepreneur Training",
        "url": "https://www.kitchentown.com/",
        "city": "San Mateo",
        "format": "In-person",
        "duration": "Self-paced + 8-week cohort options",
        "cost": "Paid (scholarships available)",
        "level": "any",
        "fields": ["food entrepreneurship", "packaged food production", "CPG"],
        "audience": "Aspiring food founders, immigrant women with culinary backgrounds",
        "outcomes": "Commercial kitchen access, regulatory help, co-packing intros",
        "languages": ["English", "Spanish"],
        "next_step": "Tour Kitchen Town at kitchentown.com",
    },
    {
        "id": "p10",
        "name": "MAA — Maitri Career & Empowerment",
        "url": "https://maitri.org/",
        "city": "Santa Clara / Sunnyvale",
        "format": "In-person + hybrid",
        "duration": "Rolling",
        "cost": "Free",
        "level": "entry to professional",
        "fields": ["healthcare admin", "tech (QA, BA)", "early childhood", "small business"],
        "audience": "South Asian immigrant women, especially survivors of domestic violence",
        "outcomes": "Career counseling, certification scholarships, legal & housing wraparound",
        "languages": ["English", "Hindi", "Bengali", "Tamil", "Telugu", "Urdu", "Punjabi"],
        "next_step": "Confidential intake at maitri.org/get-help",
    },
    {
        "id": "p11",
        "name": "Narika — Economic Empowerment",
        "url": "https://www.narika.org/",
        "city": "Fremont",
        "format": "In-person",
        "duration": "Rolling",
        "cost": "Free",
        "level": "entry to mid",
        "fields": ["caregiving (CNA prep)", "office admin", "computer literacy", "financial literacy"],
        "audience": "South Asian immigrant women, primary focus on survivors",
        "outcomes": "Vocational training stipends, ESL support, job placement",
        "languages": ["English", "Hindi", "Bengali", "Punjabi", "Urdu"],
        "next_step": "Call (800) 215-7308 (confidential) or visit narika.org",
    },
    {
        "id": "p12",
        "name": "ALAS — Mujeres Latinas en Acción",
        "url": "https://www.alasaction.org/",
        "city": "Half Moon Bay / San Mateo Coast",
        "format": "In-person",
        "duration": "Cohort-based",
        "cost": "Free",
        "level": "entry",
        "fields": ["agriculture support", "domestic work", "early childhood", "ESL+jobs"],
        "audience": "Latina immigrant women",
        "outcomes": "ESL + job-skill bundles, employer matching, leadership cohort",
        "languages": ["Spanish", "English"],
        "next_step": "Visit alasaction.org or call the Half Moon Bay office",
    },
    {
        "id": "p13",
        "name": "TechSF — SF OEWD Tech Training",
        "url": "https://oewd.org/techsf",
        "city": "San Francisco",
        "format": "In-person + hybrid",
        "duration": "Varies (4–16 weeks per track)",
        "cost": "Free for SF residents",
        "level": "entry to mid",
        "fields": ["IT support", "cybersecurity", "data analytics", "UX design", "web dev"],
        "audience": "SF residents, prioritized for women, immigrants, underemployed",
        "outcomes": "Industry certifications + direct hiring partner pipeline",
        "languages": ["English"],
        "next_step": "Apply at oewd.org/techsf",
    },
    {
        "id": "p14",
        "name": "Hopelink Adult Education / Mission Hiring Hall",
        "url": "https://www.missionhiringhall.org/",
        "city": "San Francisco (Mission)",
        "format": "In-person",
        "duration": "Rolling",
        "cost": "Free",
        "level": "entry",
        "fields": ["construction trades", "healthcare aide", "hospitality", "logistics"],
        "audience": "SF residents, prioritizing low-income and immigrant communities",
        "outcomes": "Pre-apprenticeship programs, direct employer placement",
        "languages": ["English", "Spanish", "Cantonese"],
        "next_step": "Walk in or visit missionhiringhall.org",
    },
    {
        "id": "p15",
        "name": "Bay Area Community Resources — Women's Empowerment",
        "url": "https://bacr.org/",
        "city": "San Rafael / multiple Bay Area sites",
        "format": "Hybrid",
        "duration": "Rolling cohorts",
        "cost": "Free",
        "level": "entry",
        "fields": ["administrative support", "early childhood", "community health worker"],
        "audience": "Low-income women including immigrants",
        "outcomes": "Wraparound services + job placement",
        "languages": ["English", "Spanish"],
        "next_step": "Contact intake at bacr.org",
    },
    {
        "id": "p16",
        "name": "Hack Bright Academy — Software Engineering Fellowship for Women",
        "url": "https://hackbrightacademy.com/",
        "city": "San Francisco",
        "format": "Full-time in-person",
        "duration": "12 weeks",
        "cost": "Paid (deferred tuition + scholarships)",
        "level": "professional pivot",
        "fields": ["full-stack software engineering"],
        "audience": "Women, gender-expansive, with some prior coding curiosity",
        "outcomes": "Software engineer placement; strong outcomes for career-pivoters",
        "languages": ["English"],
        "next_step": "Attend free intro workshop at hackbrightacademy.com",
    },
    {
        "id": "p17",
        "name": "AlumNI — Bay Area Healthcare Careers Pathway",
        "url": "https://www.healthworkforcecollab.org/",
        "city": "Oakland / SF",
        "format": "Hybrid",
        "duration": "8–24 weeks per credential",
        "cost": "Subsidized for low-income residents",
        "level": "entry to mid",
        "fields": ["medical assistant", "phlebotomy", "CNA", "patient care tech"],
        "audience": "Low-income Bay Area residents, immigrants welcome",
        "outcomes": "Industry-recognized credential + Kaiser / Sutter / Alameda Health hiring pipeline",
        "languages": ["English", "Spanish"],
        "next_step": "Apply at healthworkforcecollab.org",
    },
    {
        "id": "p18",
        "name": "BiasSync / WomenHack — Mentorship + Tech Placement",
        "url": "https://www.womenhack.com/",
        "city": "Bay Area events + remote",
        "format": "Online + in-person mixers",
        "duration": "Ongoing",
        "cost": "Free for job-seekers",
        "level": "professional",
        "fields": ["software engineering", "product management", "design", "data"],
        "audience": "Women in tech, all career stages",
        "outcomes": "Direct hiring events with vetted employers",
        "languages": ["English"],
        "next_step": "Sign up for next Bay Area event at womenhack.com",
    },
    {
        "id": "p19",
        "name": "PowerToFly — Career Coaching for Women",
        "url": "https://powertofly.com/",
        "city": "Remote (Bay Area employers)",
        "format": "Online",
        "duration": "Self-paced + cohort coaching",
        "cost": "Free job-seeker tier",
        "level": "professional",
        "fields": ["software", "marketing", "sales", "product", "people ops"],
        "audience": "Women and non-binary professionals",
        "outcomes": "Curated remote/hybrid roles, salary transparency, coaching",
        "languages": ["English"],
        "next_step": "Create a profile at powertofly.com",
    },
    {
        "id": "p20",
        "name": "Asian Women's Shelter — Workforce Bridge",
        "url": "https://www.sfaws.org/",
        "city": "San Francisco",
        "format": "In-person + hybrid",
        "duration": "Rolling",
        "cost": "Free",
        "level": "entry",
        "fields": ["caregiving", "office support", "food service"],
        "audience": "API immigrant women, primary focus on survivors of violence",
        "outcomes": "Multilingual job-search support, ESL, legal & housing wraparound",
        "languages": ["English", "Mandarin", "Cantonese", "Korean", "Vietnamese", "Japanese", "Thai"],
        "next_step": "24-hour multilingual line: 1-877-751-0880",
    },
    {
        "id": "p21",
        "name": "Compass Family Services — Career Forward",
        "url": "https://www.compass-sf.org/",
        "city": "San Francisco",
        "format": "In-person",
        "duration": "Rolling",
        "cost": "Free",
        "level": "entry",
        "fields": ["administrative", "early childhood", "retail mgmt"],
        "audience": "Mothers experiencing housing instability",
        "outcomes": "Job placement + housing + childcare wraparound",
        "languages": ["English", "Spanish"],
        "next_step": "Walk-in services at 37 Grove Street, SF",
    },
    {
        "id": "p22",
        "name": "SmartTalent Bay Area — Apprenticeship Programs",
        "url": "https://www.dol.gov/agencies/eta/apprenticeship",
        "city": "Bay Area-wide",
        "format": "On-the-job",
        "duration": "1–4 years (paid throughout)",
        "cost": "Paid apprenticeship",
        "level": "entry to professional",
        "fields": ["healthcare", "IT / cybersecurity", "construction", "advanced manufacturing"],
        "audience": "Anyone 18+ with HS diploma; women and immigrants encouraged",
        "outcomes": "Earn-while-you-learn; nationally portable journey-worker credentials",
        "languages": ["English"],
        "next_step": "Search Bay Area apprenticeships at apprenticeship.gov",
    },
    {
        "id": "p23",
        "name": "Self-eSTEM",
        "url": "https://www.selfestem.org/",
        "city": "Oakland",
        "format": "In-person + virtual",
        "duration": "Year-round",
        "cost": "Free",
        "level": "entry / youth",
        "fields": ["STEM exposure", "engineering", "tech entrepreneurship"],
        "audience": "Girls and young women of color (8–24), incl. immigrants",
        "outcomes": "STEM scholarships, mentorship, college and career pipeline",
        "languages": ["English", "Spanish"],
        "next_step": "Programs at selfestem.org/programs",
    },
    {
        "id": "p24",
        "name": "Pivot Tech School — Women & Underrepresented Tech",
        "url": "https://www.pivottechschool.com/",
        "city": "Remote (Oakland HQ)",
        "format": "Online",
        "duration": "12–24 weeks",
        "cost": "Income share / scholarships",
        "level": "career-pivot",
        "fields": ["UX/UI design", "front-end dev", "product management"],
        "audience": "Women, BIPOC, LGBTQ+, immigrants",
        "outcomes": "Portfolio + employer partner pipeline",
        "languages": ["English"],
        "next_step": "Apply at pivottechschool.com",
    },
    {
        "id": "p25",
        "name": "California ESL + Vocational Bridge (LaborSearch)",
        "url": "https://www.edd.ca.gov/jobs_and_training/",
        "city": "Statewide",
        "format": "In-person + online",
        "duration": "Varies",
        "cost": "Free for WIOA-eligible",
        "level": "entry",
        "fields": ["healthcare aide", "office support", "logistics", "manufacturing"],
        "audience": "WIOA-eligible adults, including new immigrants with work auth.",
        "outcomes": "ESL + skills + state-funded placement coaching",
        "languages": ["English", "Spanish", "Mandarin", "Cantonese", "Vietnamese", "Tagalog"],
        "next_step": "Visit your local America's Job Center of California (AJCC)",
    },
    {
        "id": "p26",
        "name": "Bay Area Girls Who Code — Adult Pathways",
        "url": "https://girlswhocode.com/",
        "city": "Bay Area + remote",
        "format": "Online",
        "duration": "Self-paced",
        "cost": "Free",
        "level": "entry",
        "fields": ["software engineering", "computer science fundamentals"],
        "audience": "Women and non-binary; immigrant women welcome",
        "outcomes": "Career community + intro coursework",
        "languages": ["English"],
        "next_step": "Create a free account at girlswhocode.com/college-loop",
    },
    {
        "id": "p27",
        "name": "Project SafeSpace — Employment for Survivor Mothers",
        "url": "https://www.lapcc.org/",
        "city": "Lake County / North Bay",
        "format": "In-person",
        "duration": "Rolling",
        "cost": "Free",
        "level": "entry",
        "fields": ["caregiving", "retail", "early childhood"],
        "audience": "Survivor mothers, immigrant women",
        "outcomes": "Childcare-during-training + job placement",
        "languages": ["English", "Spanish"],
        "next_step": "Inquire at lapcc.org/projects",
    },
    {
        "id": "p28",
        "name": "NextStep Workforce — East Bay",
        "url": "https://eastbayworks.com/",
        "city": "Alameda / Contra Costa",
        "format": "In-person + virtual",
        "duration": "Rolling",
        "cost": "Free",
        "level": "entry to mid",
        "fields": ["healthcare", "logistics", "advanced manufacturing", "IT support"],
        "audience": "East Bay residents, immigrants welcome with work auth.",
        "outcomes": "Skills training + AJCC employer pipeline",
        "languages": ["English", "Spanish", "Mandarin"],
        "next_step": "Walk in to your local AJCC",
    },
    {
        "id": "p29",
        "name": "WomenHack Mentor Bridge — Bay Area Chapter",
        "url": "https://www.bayareawomenintech.com/",
        "city": "Bay Area",
        "format": "Online + in-person",
        "duration": "Ongoing",
        "cost": "Free",
        "level": "professional",
        "fields": ["product mgmt", "engineering", "design", "leadership"],
        "audience": "Women in tech, mid-career and senior",
        "outcomes": "1:1 mentorship, exec coaching, hiring intros",
        "languages": ["English"],
        "next_step": "Join the chapter at bayareawomenintech.com",
    },
    {
        "id": "p30",
        "name": "Stride Bay Area — Returnship for Career-Gap Professionals",
        "url": "https://www.stridesearch.com/",
        "city": "Remote + SF",
        "format": "Hybrid",
        "duration": "12-week paid returnship",
        "cost": "Paid",
        "level": "professional (career re-entry)",
        "fields": ["product mgmt", "engineering", "marketing", "ops"],
        "audience": "Professionals returning after a 1+ year career break (incl. caregiving / health)",
        "outcomes": "Paid return-to-work program with hiring conversion",
        "languages": ["English"],
        "next_step": "Apply for upcoming cohorts at stridesearch.com",
    },
]
